
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: chatdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/configdb/mongodb-keyfile"]
    volumes:
      - ./mongodb_data:/data/db
      - ./mongodb-keyfile:/data/configdb/mongodb-keyfile